import json
import os
null = None

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Quantifying Fairness in CPU Scheduling\n",
    "This interactive notebook demonstrates the execution of **First-Come, First-Served (FCFS)**, **Priority Scheduling**, **Round Robin (RR)**, **Shortest Job First (SJF)**, and **Priority with Aging** using genuine supercomputer workloads from the Parallel Workloads Archive.\n",
    "\n",
    "The analysis measures advanced queueing metrics including *Average Waiting Time*, *Bounded Slowdown*, *Wait Time CV*, *Jain's Fairness Index*, *Makespan*, *Average Queue Length*, and *Starvation Rates* across 10 real-world HPC traces."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import os\n",
    "\n",
    "sns.set_style(\"whitegrid\")\n",
    "plt.rcParams['figure.figsize'] = (14, 8)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1. Data Loader & Generator\n",
    "Here we parse the raw `.swf` format traces. Synthetic datasets were removed to maintain strict real-world credibility."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_swf(filename, max_rows=200):\n",
    "    data = []\n",
    "    if not os.path.exists(filename):\n",
    "        print(f\"Warning: {filename} not found.\")\n",
    "        return pd.DataFrame()\n",
    "        \n",
    "    with open(filename, 'r') as f:\n",
    "        count = 0\n",
    "        for line in f:\n",
    "            line = line.strip()\n",
    "            if not line or line.startswith(';'): continue\n",
    "            parts = line.split()\n",
    "            if len(parts) < 18: continue\n",
    "            try:\n",
    "                pid = int(parts[0])\n",
    "                submit = float(parts[1])\n",
    "                run = float(parts[3])\n",
    "                req_procs = int(parts[7])\n",
    "                if run <= 0: run = 1 # give it at least 1ms to avoid DIV/0\n",
    "                prio = min(10, max(1, req_procs)) # proxy priority based on requested processors\n",
    "                data.append({'pid': pid, 'arrivalTime': submit, 'priority': prio, 'processTime': int(run)})\n",
    "                count += 1\n",
    "                if count >= max_rows: break\n",
    "            except ValueError:\n",
    "                continue\n",
    "    df = pd.DataFrame(data)\n",
    "    if not df.empty:\n",
    "        df.sort_values(by='arrivalTime', inplace=True)\n",
    "        df['arrivalTime'] = df['arrivalTime'] - df['arrivalTime'].min()\n",
    "    return df\n",
    "\n",
    "def generate_datasets():\n",
    "    datasets = {}\n",
    "    n_processes = 564\n",
    "\n",
    "    # 10 Real World Traces:\n",
    "    datasets['Real SDSC SP2'] = load_swf('SDSC-SP2.swf', n_processes)\n",
    "    datasets['Real SDSC BLUE'] = load_swf('SDSC-BLUE.swf', n_processes)\n",
    "    datasets['Real ANL Intrepid'] = load_swf('ANL-Intrepid.swf', n_processes)\n",
    "    datasets['Real CTC SP2'] = load_swf('CTC-SP2.swf', n_processes)\n",
    "    datasets['Real HPC2N'] = load_swf('HPC2N.swf', n_processes)\n",
    "    datasets['Real KTH SP2'] = load_swf('KTH-SP2.swf', n_processes)\n",
    "    datasets['Real CEA Curie'] = load_swf('CEA-Curie.swf', n_processes)\n",
    "    datasets['Real PIK IPLEX'] = load_swf('PIK-IPLEX.swf', n_processes)\n",
    "    datasets['Real RICC'] = load_swf('RICC.swf', n_processes)\n",
    "    datasets['Real Lublin'] = load_swf('Lublin-1024.swf', n_processes)\n",
    "\n",
    "    # Note: excluding the synthetic ones entirely this time per user request. \n",
    "    return {k: v for k, v in datasets.items() if not v.empty}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2. Fairness Metrics Calculator\n",
    "This function computes advanced queueing metrics including CV of Wait Time, Max Bounded Slowdown, Makespan, and Little's Law Queue Length."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_extended_metrics(df, total_time, quantum=None):\n",
    "    df[\"TurnaroundTime\"] = df[\"FinishTime\"] - df[\"arrivalTime\"]\n",
    "    df[\"WaitingTime\"] = df[\"TurnaroundTime\"] - df[\"processTime\"]\n",
    "    df[\"ResponseTime\"] = df[\"StartTime\"] - df[\"arrivalTime\"]\n",
    "    \n",
    "    metrics = {}\n",
    "    metrics['AWT'] = df[\"WaitingTime\"].mean()\n",
    "    metrics['ATAT'] = df[\"TurnaroundTime\"].mean()\n",
    "    metrics['Response Time'] = df[\"ResponseTime\"].mean()\n",
    "    metrics['Bounded Slowdown'] = (df[\"TurnaroundTime\"] / df[\"processTime\"]).mean()\n",
    "    metrics['Max Bounded Slowdown'] = (df[\"TurnaroundTime\"] / df[\"processTime\"]).max()\n",
    "    metrics['WT Variance'] = df[\"WaitingTime\"].var() if len(df) > 1 else 0\n",
    "    metrics['WT CV'] = df[\"WaitingTime\"].std() / df[\"WaitingTime\"].mean() if df[\"WaitingTime\"].mean() > 0 else 0\n",
    "    metrics['MWT'] = df[\"WaitingTime\"].max()\n",
    "    metrics['Throughput'] = len(df) / total_time if total_time > 0 else 0\n",
    "    \n",
    "    total_burst = df[\"processTime\"].sum()\n",
    "    metrics['CPU Utilization (%)'] = (total_burst / total_time) * 100 if total_time > 0 else 0\n",
    "    \n",
    "    makespan = df[\"FinishTime\"].max() - df[\"arrivalTime\"].min()\n",
    "    metrics['Makespan'] = makespan if makespan > 0 else 0\n",
    "    metrics['Average Queue Length'] = (len(df) / makespan) * metrics['AWT'] if makespan > 0 else 0\n",
    "    \n",
    "    # 2. Resource waste/idle time\n",
    "    first_arrival = df[\"arrivalTime\"].min()\n",
    "    idle_time = total_time - total_burst - first_arrival\n",
    "    metrics['Idle Time'] = idle_time if idle_time > 0 else 0\n",
    "    \n",
    "    sum_wt = df[\"WaitingTime\"].sum()\n",
    "    sum_sq_wt = (df[\"WaitingTime\"]**2).sum()\n",
    "    n = len(df)\n",
    "    metrics['JFI'] = (sum_wt**2) / (n * sum_sq_wt) if sum_sq_wt > 0 else 1.0\n",
    "    \n",
    "    def gini(array):\n",
    "        array = np.sort(array)\n",
    "        index = np.arange(1, array.shape[0] + 1)\n",
    "        nn = array.shape[0]\n",
    "        return (np.sum((2 * index - nn  - 1) * array)) / (nn * np.sum(array)) if np.sum(array) > 0 else 0\n",
    "    metrics['Gini (WT)'] = gini(df[\"WaitingTime\"].values)\n",
    "    \n",
    "    avg_burst = df[\"processTime\"].mean()\n",
    "    starvation_threshold = 3 * avg_burst\n",
    "    metrics['Starvation Count'] = len(df[df[\"WaitingTime\"] > starvation_threshold])\n",
    "    metrics['Starvation Rate (%)'] = (metrics['Starvation Count'] / n) * 100 if n > 0 else 0\n",
    "    \n",
    "    # 1. Preemption frequency\n",
    "    # 8. Dynamic task switching efficiency\n",
    "    cs_count = len(df)\n",
    "    if 'Preemptions' in df.columns:\n",
    "        cs_count += df['Preemptions'].sum()\n",
    "    metrics['Preemption Frequency'] = cs_count / n if n > 0 else 0\n",
    "    \n",
    "    # Assuming 0.1 time unit per context switch\n",
    "    cs_overhead = 0.1 * cs_count\n",
    "    metrics['Task Switching Eff (%)'] = (total_burst / (total_burst + cs_overhead)) * 100 if (total_burst + cs_overhead) > 0 else 0\n",
    "\n",
    "    # 3. Priority inversion potential\n",
    "    # If a high priority job arrived and is waiting while a lower priority job is executing\n",
    "    inversion_count = 0\n",
    "    # 5. Fairness bias / fairness to low-priority jobs\n",
    "    # Correlation between priority and waiting time.\n",
    "    # Higher priority (lower number in typical OS, but here we used min(10, req_procs), let's keep it straight metric-wise)\n",
    "    # The higher the value of 'priority' column here, the higher the \"priority\".\n",
    "    # A negative correlation means higher priority gets lower waiting time (fairness to priority, bias against low).\n",
    "    \n",
    "    if n > 0:\n",
    "        for idx, row in df.iterrows():\n",
    "            arr, prio = row['arrivalTime'], row['priority']\n",
    "            # Find jobs with lower priority that were executing when this higher priority job arrived\n",
    "            # This is simpler logic just evaluating temporal overlap\n",
    "            if prio > 1:\n",
    "                lower_prio_executing = df[(df['priority'] < prio) & (df['StartTime'] < arr) & (df['FinishTime'] > arr)]\n",
    "                if not lower_prio_executing.empty:\n",
    "                    inversion_count += len(lower_prio_executing)\n",
    "                    \n",
    "        metrics['Priority Inversion Potential'] = inversion_count\n",
    "        \n",
    "        # Pearson correlation\n",
    "        std_prio = df['priority'].std()\n",
    "        std_wt = df['WaitingTime'].std()\n",
    "        if std_prio > 0 and std_wt > 0:\n",
    "            metrics['Fairness Bias (Corr)'] = df['priority'].corr(df['WaitingTime'])\n",
    "        else:\n",
    "            metrics['Fairness Bias (Corr)'] = 0.0\n",
    "            \n",
    "    # 6. Fairness over time\n",
    "    # Split the dataset into first half and second half temporally\n",
    "    if n > 1:\n",
    "        mid_time = first_arrival + (total_time - first_arrival) / 2\n",
    "        df_first = df[df['arrivalTime'] <= mid_time]\n",
    "        df_second = df[df['arrivalTime'] > mid_time]\n",
    "        \n",
    "        def safe_jfi(sub_df):\n",
    "            if sub_df.empty: return 1.0\n",
    "            s_wt = sub_df[\"WaitingTime\"].sum()\n",
    "            ss_wt = (sub_df[\"WaitingTime\"]**2).sum()\n",
    "            return (s_wt**2) / (len(sub_df) * ss_wt) if ss_wt > 0 else 1.0\n",
    "            \n",
    "        metrics['JFI First Half'] = safe_jfi(df_first)\n",
    "        metrics['JFI Second Half'] = safe_jfi(df_second)\n",
    "    else:\n",
    "        metrics['JFI First Half'] = 1.0\n",
    "        metrics['JFI Second Half'] = 1.0\n",
    "\n",
    "    # 7. Throughput vs. fairness metric \n",
    "    # Ratio of Throughput to Gini Inequality index - higher is better performance-fairness balance\n",
    "    gt = metrics['Gini (WT)']\n",
    "    metrics['Throughput to Gini'] = metrics['Throughput'] / gt if gt > 0 else metrics['Throughput']\n",
    "\n",
    "    # NEW METRICS SYNCED FROM run_scheduling_analysis.py\n",
    "    metrics['NTT'] = (df[\"TurnaroundTime\"] / df[\"processTime\"]).mean()\n",
    "    metrics['WT P95'] = np.percentile(df[\"WaitingTime\"], 95)\n",
    "    metrics['RT P95'] = np.percentile(df[\"ResponseTime\"], 95)\n",
    "    \n",
    "    if makespan > 0 and n > 10:\n",
    "        n_windows = 10\n",
    "        window_size = makespan / n_windows\n",
    "        window_utilizations = []\n",
    "        for i in range(n_windows):\n",
    "            window_start = first_arrival + i * window_size\n",
    "            window_end = window_start + window_size\n",
    "            window_jobs = df[(df['StartTime'] < window_end) & (df['FinishTime'] > window_start)]\n",
    "            window_cpu_time = 0\n",
    "            for _, job in window_jobs.iterrows():\n",
    "                overlap_start = max(job['StartTime'], window_start)\n",
    "                overlap_end = min(job['FinishTime'], window_end)\n",
    "                window_cpu_time += max(0, overlap_end - overlap_start)\n",
    "            window_util = (window_cpu_time / window_size) * 100 if window_size > 0 else 0\n",
    "            window_utilizations.append(window_util)\n",
    "        metrics['Load Imbalance Factor'] = np.std(window_utilizations)\n",
    "    else:\n",
    "        metrics['Load Imbalance Factor'] = 0\n",
    "\n",
    "    if n > 10:\n",
    "        long_threshold = np.percentile(df[\"processTime\"], 90)\n",
    "        long_jobs = df[df[\"processTime\"] >= long_threshold]\n",
    "        short_jobs = df[df[\"processTime\"] < long_threshold]\n",
    "        convoy_delay = 0\n",
    "        for _, short_job in short_jobs.iterrows():\n",
    "            for _, long_job in long_jobs.iterrows():\n",
    "                if (short_job['arrivalTime'] > long_job['arrivalTime'] and \n",
    "                    short_job['StartTime'] > long_job['StartTime'] and\n",
    "                    short_job['StartTime'] < long_job['FinishTime']):\n",
    "                    convoy_delay += min(long_job['FinishTime'] - short_job['StartTime'], short_job['WaitingTime'])\n",
    "        metrics['Convoy Effect'] = convoy_delay / len(short_jobs) if len(short_jobs) > 0 else 0\n",
    "    else:\n",
    "        metrics['Convoy Effect'] = 0\n",
    "        \n",
    "    df['ResponseRatio'] = (df['WaitingTime'] + df['processTime']) / df['processTime']\n",
    "    metrics['Avg Response Ratio'] = df['ResponseRatio'].mean()\n",
    "    priority_weights = df['priority'] / df['priority'].sum() if df['priority'].sum() > 0 else np.ones(n) / n\n",
    "    metrics['Weighted TAT'] = (df['TurnaroundTime'] * priority_weights).sum()\n",
    "    \n",
    "    ntt_array = df[\"TurnaroundTime\"] / df[\"processTime\"]\n",
    "    metrics['Predictability CV'] = ntt_array.std() / ntt_array.mean() if ntt_array.mean() > 0 else 0\n",
    "    metrics['Avg Stretch'] = ntt_array.mean()\n",
    "    metrics['Service Time CV'] = df[\"processTime\"].std() / df[\"processTime\"].mean() if df[\"processTime\"].mean() > 0 else 0\n",
    "    \n",
    "    if n > 10:\n",
    "        small_threshold = np.percentile(df[\"processTime\"], 33)\n",
    "        large_threshold = np.percentile(df[\"processTime\"], 67)\n",
    "        small_jobs_wt = df[df[\"processTime\"] <= small_threshold][\"WaitingTime\"]\n",
    "        large_jobs_wt = df[df[\"processTime\"] >= large_threshold][\"WaitingTime\"]\n",
    "        metrics['Size Fairness Ratio'] = (small_jobs_wt.mean() / large_jobs_wt.mean()) if len(large_jobs_wt) > 0 and large_jobs_wt.mean() > 0 else 1.0\n",
    "    else:\n",
    "        metrics['Size Fairness Ratio'] = 1.0\n",
    "\n",
    "    return metrics"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Schedulers (FCFS, Priority, SJF, Priority with Aging, Round Robin)\n",
    "Simulating the specific dispatch logic algorithm by algorithm."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def fcfs_schedule(df_in):\n",
    "    df = df_in.copy().sort_values(by='arrivalTime').reset_index(drop=True)\n",
    "    current_time = 0\n",
    "    start_times, finish_times = [], []\n",
    "    for arr, burst in zip(df['arrivalTime'], df['processTime']):\n",
    "        start = max(current_time, arr)\n",
    "        start_times.append(start)\n",
    "        finish = start + burst\n",
    "        finish_times.append(finish)\n",
    "        current_time = finish\n",
    "    df['StartTime'] = start_times\n",
    "    df['FinishTime'] = finish_times\n",
    "    df['Preemptions'] = 0\n",
    "    return df, current_time\n",
    "\n",
    "def priority_schedule(df_in): \n",
    "    # Non-preemptive, higher number = higher priority\n",
    "    df = df_in.copy().sort_values(by=['arrivalTime', 'priority'], ascending=[True, False]).reset_index(drop=True)\n",
    "    current_time = 0\n",
    "    completed = 0\n",
    "    n = len(df)\n",
    "    \n",
    "    start_times = np.zeros(n)\n",
    "    finish_times = np.zeros(n)\n",
    "    is_completed = np.zeros(n, dtype=bool)\n",
    "    \n",
    "    while completed < n:\n",
    "        arrived = df[(df['arrivalTime'] <= current_time) & (~is_completed)]\n",
    "        if arrived.empty:\n",
    "            next_arrival = df.loc[~is_completed, 'arrivalTime'].min()\n",
    "            current_time = next_arrival\n",
    "            arrived = df[(df['arrivalTime'] <= current_time) & (~is_completed)]\n",
    "            \n",
    "        # Pick highest priority\n",
    "        idx = arrived['priority'].idxmax()\n",
    "        start = current_time\n",
    "        burst = df.loc[idx, 'processTime']\n",
    "        finish = start + burst\n",
    "        \n",
    "        start_times[idx] = start\n",
    "        finish_times[idx] = finish\n",
    "        is_completed[idx] = True\n",
    "        \n",
    "        current_time = finish\n",
    "        completed += 1\n",
    "        \n",
    "    df['StartTime'] = start_times\n",
    "    df['FinishTime'] = finish_times\n",
    "    df['Preemptions'] = 0\n",
    "    return df, current_time\n",
    "\n",
    "def sjf_schedule(df_in):\n",
    "    # Non-preemptive Shortest Job First\n",
    "    df = df_in.copy().sort_values(by=['arrivalTime', 'processTime']).reset_index(drop=True)\n",
    "    current_time = 0\n",
    "    completed = 0\n",
    "    n = len(df)\n",
    "    \n",
    "    start_times = np.zeros(n)\n",
    "    finish_times = np.zeros(n)\n",
    "    is_completed = np.zeros(n, dtype=bool)\n",
    "    \n",
    "    while completed < n:\n",
    "        arrived = df[(df['arrivalTime'] <= current_time) & (~is_completed)]\n",
    "        if arrived.empty:\n",
    "            next_arrival = df.loc[~is_completed, 'arrivalTime'].min()\n",
    "            current_time = next_arrival\n",
    "            arrived = df[(df['arrivalTime'] <= current_time) & (~is_completed)]\n",
    "            \n",
    "        # Pick shortest burst time\n",
    "        idx = arrived['processTime'].idxmin()\n",
    "        start = current_time\n",
    "        burst = df.loc[idx, 'processTime']\n",
    "        finish = start + burst\n",
    "        \n",
    "        start_times[idx] = start\n",
    "        finish_times[idx] = finish\n",
    "        is_completed[idx] = True\n",
    "        \n",
    "        current_time = finish\n",
    "        completed += 1\n",
    "        \n",
    "    df['StartTime'] = start_times\n",
    "    df['FinishTime'] = finish_times\n",
    "    df['Preemptions'] = 0\n",
    "    return df, current_time\n",
    "\n",
    "def priority_aging_schedule(df_in): \n",
    "    # Non-preemptive Priority with Aging\n",
    "    df = df_in.copy().sort_values(by=['arrivalTime', 'priority'], ascending=[True, False]).reset_index(drop=True)\n",
    "    current_time = 0\n",
    "    completed = 0\n",
    "    n = len(df)\n",
    "    \n",
    "    start_times = np.zeros(n)\n",
    "    finish_times = np.zeros(n)\n",
    "    is_completed = np.zeros(n, dtype=bool)\n",
    "    \n",
    "    aging_interval = df['processTime'].mean() * 10 \n",
    "    if aging_interval <= 0: aging_interval = 1000\n",
    "    \n",
    "    while completed < n:\n",
    "        arrived = df[(df['arrivalTime'] <= current_time) & (~is_completed)].copy()\n",
    "        if arrived.empty:\n",
    "            next_arrival = df.loc[~is_completed, 'arrivalTime'].min()\n",
    "            current_time = next_arrival\n",
    "            arrived = df[(df['arrivalTime'] <= current_time) & (~is_completed)].copy()\n",
    "            \n",
    "        arrived['dynamic_priority'] = arrived['priority'] + ((current_time - arrived['arrivalTime']) / aging_interval)\n",
    "        idx = arrived['dynamic_priority'].idxmax()\n",
    "        start = current_time\n",
    "        burst = df.loc[idx, 'processTime']\n",
    "        finish = start + burst\n",
    "        \n",
    "        start_times[idx] = start\n",
    "        finish_times[idx] = finish\n",
    "        is_completed[idx] = True\n",
    "        \n",
    "        current_time = finish\n",
    "        completed += 1\n",
    "        \n",
    "    df['StartTime'] = start_times\n",
    "    df['FinishTime'] = finish_times\n",
    "    df['Preemptions'] = 0\n",
    "    return df, current_time\n",
    "\n",
    "def round_robin_schedule(df_in, quantum):\n",
    "    df = df_in.copy().sort_values(by='arrivalTime').reset_index(drop=True)\n",
    "    n = len(df)\n",
    "    remaining_burst = df['processTime'].values.copy()\n",
    "    start_times = np.full(n, -1.0)\n",
    "    finish_times = np.zeros(n)\n",
    "    preemptions = np.zeros(n)\n",
    "    \n",
    "    current_time = 0\n",
    "    completed = 0\n",
    "    queue = []\n",
    "    idx_arrived = 0\n",
    "    \n",
    "    while completed < n:\n",
    "        while idx_arrived < n and df.loc[idx_arrived, 'arrivalTime'] <= current_time:\n",
    "            queue.append(idx_arrived)\n",
    "            idx_arrived += 1\n",
    "            \n",
    "        if not queue:\n",
    "            current_time = df.loc[idx_arrived, 'arrivalTime']\n",
    "            continue\n",
    "            \n",
    "        curr_proc = queue.pop(0)\n",
    "        if start_times[curr_proc] == -1:\n",
    "            start_times[curr_proc] = current_time\n",
    "            \n",
    "        time_to_run = min(quantum, remaining_burst[curr_proc])\n",
    "        current_time += time_to_run\n",
    "        remaining_burst[curr_proc] -= time_to_run\n",
    "        \n",
    "        while idx_arrived < n and df.loc[idx_arrived, 'arrivalTime'] <= current_time:\n",
    "            queue.append(idx_arrived)\n",
    "            idx_arrived += 1\n",
    "            \n",
    "        if remaining_burst[curr_proc] == 0:\n",
    "            finish_times[curr_proc] = current_time\n",
    "            completed += 1\n",
    "        else:\n",
    "            queue.append(curr_proc)\n",
    "            preemptions[curr_proc] += 1\n",
    "            \n",
    "    df['StartTime'] = start_times\n",
    "    df['FinishTime'] = finish_times\n",
    "    df['Preemptions'] = preemptions\n",
    "    return df, current_time"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 4. Running the Analysis and Presenting Results\n",
    "Executing the simulations across all datasets and charting out the results contextually inline."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "datasets = generate_datasets()\n",
    "all_results = []\n",
    "\n",
    "for ds_name, ds_df in datasets.items():\n",
    "    mean_burst = ds_df['processTime'].mean()\n",
    "    quantum = int(mean_burst / 2) if int(mean_burst / 2) > 0 else 1\n",
    "    \n",
    "    res_fcfs, tt_fcfs = fcfs_schedule(ds_df)\n",
    "    m_fcfs = calculate_extended_metrics(res_fcfs, tt_fcfs)\n",
    "    m_fcfs['Algorithm'] = 'FCFS'\n",
    "    m_fcfs['Dataset'] = ds_name\n",
    "    \n",
    "    res_prio, tt_prio = priority_schedule(ds_df)\n",
    "    m_prio = calculate_extended_metrics(res_prio, tt_prio)\n",
    "    m_prio['Algorithm'] = 'Priority'\n",
    "    m_prio['Dataset'] = ds_name\n",
    "    \n",
    "    res_rr, tt_rr = round_robin_schedule(ds_df, quantum)\n",
    "    m_rr = calculate_extended_metrics(res_rr, tt_rr, quantum)\n",
    "    m_rr['Algorithm'] = 'Round Robin'\n",
    "    m_rr['Dataset'] = ds_name\n",
    "    \n",
    "    res_sjf, tt_sjf = sjf_schedule(ds_df)\n",
    "    m_sjf = calculate_extended_metrics(res_sjf, tt_sjf)\n",
    "    m_sjf['Algorithm'] = 'SJF'\n",
    "    m_sjf['Dataset'] = ds_name\n",
    "\n",
    "    res_prio_aging, tt_prio_aging = priority_aging_schedule(ds_df)\n",
    "    m_prio_aging = calculate_extended_metrics(res_prio_aging, tt_prio_aging)\n",
    "    m_prio_aging['Algorithm'] = 'Priority (Aging)'\n",
    "    m_prio_aging['Dataset'] = ds_name\n",
    "    \n",
    "    all_results.extend([m_fcfs, m_prio, m_rr, m_sjf, m_prio_aging])\n",
    "\n",
    "results_df = pd.DataFrame(all_results)\n",
    "display(results_df.head(10))\n",
    "\n",
    "metrics_to_plot = [\n",
    "    'AWT', 'Response Time', 'Bounded Slowdown', 'Max Bounded Slowdown', 'WT CV', 'JFI', 'Starvation Rate (%)', \n",
    "    'Makespan', 'Average Queue Length', 'NTT', 'WT P95', 'RT P95', 'Convoy Effect', 'Predictability CV', 'Size Fairness Ratio'\n",
    "]\n",
    "for metric in metrics_to_plot:\n",
    "    if metric in results_df.columns:\n",
    "        plt.figure(figsize=(12, 6))\n",
    "        sns.barplot(data=results_df, x='Dataset', y=metric, hue='Algorithm')\n",
    "        plt.title(f'{metric} Comparison across Datasets')\n",
    "        plt.xticks(rotation=45, ha='right')\n",
    "        plt.tight_layout()\n",
    "        plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('Final_Scheduling_Analysis.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print("Notebook generated successfully!")
